# supported languages: "custom" (default, english), "de" (german), "fr" (french), and "pt-BR" (brazilian portuguese).
language: custom

# changes the required sign name for the creation of land vaults
# Example: [land vault]
land_sign_vault_name: 'land'

# Prevents players from creating a vault outside a land if set to true
vaults_only_in_lands: false

# balance to start an account with (purely virtual)
land_start_balance: 0