name: gringotts-lands
version: ${project.version}
main: net.laboulangerie.gringottslands.GringottsLands
api-version: 1.19
authors: ["Clem", "Grooble", "Grôle"]
depend: [Lands, Gringotts]
commands:
    bal:
        usage: /bal <player>
        description: Give balances of the given player or the command sender
    baltop:
        usage: /baltop
        description: Give leaderboard of the tax accounts balances 
